jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az Module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
