name: Build and deploy Go app to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Test
      run: go test

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        app-name: fordae
        package: build/
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
