name: Build Go app and push to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build
        run: go build -mod=readonly -o build/go-app.exe -v

      - name: Test
        run: go test

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: fordae
          package: build/
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
