name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: window-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -0/go-app.exe -v

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: fordae
          package: build/
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3B5E464EA9774352883A2B388165B459 }}
          images: null

