name: Build and deploy Go app to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Test
      run: go test

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Print Azure credentials
      run: echo "${{ secrets.AZURE_CREDENTIALS }}"

    - name: Install Az CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Check Az CLI version
      run: az --version
      
    - name: Set empty slot name
      run: echo "slot-name=" >> $GITHUB_ENV

    - name: Deploy to Azure
      run: |
        az webapp create --resource-group MyResourceGroup --plan 1 --name fordae --runtime "DOTNET|6.0"
        az webapp deployment source config-zip --src build/go-app.zip --name fordae --resource-group rg-hg-FileExplorer


