name: Build Go app and push to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        working-directory: ./FileExplorer
        run: go build -mod=readonly -o go-app.exe -v

      - name: Test
        working-directory: ./FileExplorer
        run: go test

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: fordae
          package: .
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
