name: Build Go app and push to Azure
<<<<<<< HEAD

=======
>>>>>>> da61829c8aa0dbe4577820fddf55d2490a828d31

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
<<<<<<< HEAD
        go-version: 1.71
=======
        go-version: 1.17
>>>>>>> da61829c8aa0dbe4577820fddf55d2490a828d31

    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Test
      run: go test
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: fordae
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
