name: Build Go app and push to Azure
<<<<<<< HEAD
=======

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Test
      run: go test
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
>>>>>>> 865cced438529f264af6f403fa458f3a62fc85be
        # Name of the Azure Web App
        app-name: fordae
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
