name: Build Go app and push to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build -mod=readonly -o FileExplorer/go-app.exe -v
        working-directory: ${{ github.workspace }}

      - name: Test
        run: go test ./FileExplorer
        working-directory: ${{ github.workspace }}

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: fordae
          package: ./FileExplorer
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
