name: Build Go app and push to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build
      run: go build -o /go-app.exe -v

    - name: Test
      run: go test
      
    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: fordae
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: null