name: Build Go app and push to Azure
        # Name of the Azure Web App
        app-name: fordae
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
