name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1

    - name: Configure Azure credentials
      run: |
        az config set cloud.azure.com
        az config set extension.disable_dynamic_install=yes_without_prompt

    - name: Build
      run: go build -o build/go-app.exe -v

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          -g <rg-hg-FileExplore> \
          -n <fordae> \
          --src build/go-app.exe.zip
